/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oVxIs7l3qLH
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function addons() {
  return (
    (<Card>
      <CardHeader>
        <CardTitle>Companies</CardTitle>
        <CardDescription>Sample of companies</CardDescription>
      </CardHeader>
      <CardContent className="p-0">
        <div className="relative w-full max-w-lg mx-auto grid gap-1.5">
          <SearchIcon
            className="absolute inset-y-0 left-0 z-10 w-4 h-4 my-2 ml-2 text-gray-400 top-1/2 dark:text-gray-500" />
          <Input className="pl-8 w-full rounded-lg" placeholder="Search" type="search" />
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[100px]">Ticker</TableHead>
              <TableHead className="w-[100px]">Status</TableHead>
              <TableHead className="w-[100px]">Score</TableHead>
              <TableHead className="w-[100px]">Sentiment</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className="font-medium text-lg">AAPL</TableCell>
              <TableCell className="text-sm">Positive</TableCell>
              <TableCell>0.023</TableCell>
              <TableCell className="text-right">Bullish</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium text-lg">GOOGL</TableCell>
              <TableCell className="text-sm">Neutral</TableCell>
              <TableCell>0.000</TableCell>
              <TableCell className="text-right">Neutral</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium text-lg">TSLA</TableCell>
              <TableCell className="text-sm">Bearish</TableCell>
              <TableCell>-0.047</TableCell>
              <TableCell className="text-right">Bearish</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium text-lg">MSFT</TableCell>
              <TableCell className="text-sm">Positive</TableCell>
              <TableCell>0.075</TableCell>
              <TableCell className="text-right">Bullish</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium text-lg">NVDA</TableCell>
              <TableCell className="text-sm">Bearish</TableCell>
              <TableCell>-0.047</TableCell>
              <TableCell className="text-right">Bearish</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </CardContent>
    </Card>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
